services:
  backend-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - remotion-network

networks:
  remotion-network:
    external: true
