package constant

var (
	SuccessConnectDatabase       = "successfully connected to the database."
	SuccessMigrateDatabase       = "database migration completed successfully."
	SuccessSeedDatabase          = "database seeding completed successfully."
	SuccessLoadEnvFile           = "successfully loaded .env file."
	SuccessResetTable            = "database tables reset successfully."
	SuccessLogin                 = "successfully login!"
	SuccessRegister              = "successfully register!"
	SuccessCreateExercise        = "successfully create new exercise."
	SuccessDeleteExercise        = "successfully delete exercise"
	SuccessFetchExercises        = "successfully fetch all exercise."
	SuccessFetchExerciseDetail   = "successfully fetch exercise detail."
	SuccessFetchPatients         = "successfully fetch all patient."
	SuccessFetchPatientDetail    = "successfully fetch patient detail."
	SuccessSearchPatients        = "successfully find specific patient."
	SuccessAddPatient            = "successfully add new patient"
	SuccessEditPatient           = "successfully edit patient detail"
	SuccessAssignExercise        = "successfully assign new exercises to patient."
	SuccessEditPatientExercise   = "successfully edit patient's exercise."
	SuccessDeletePatientExercise = "successfully delete patient's exercise."
	SuccessFetchPatientPhase     = "successfully fetch patient's phase"
	SuccessFetchUsers            = "successfully fetch all user non fisio."
	SuccessAddProgress           = "successfully add progress"
	SuccessFetchProgresses       = "successfully fetch patient's progress"
)
